CREATE TABLE public.complaints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_number BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  reporter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  reporter_role public.app_role NOT NULL,
  reporter_name TEXT NOT NULL,
  reporter_employee_id TEXT,
  subject_employee_id TEXT REFERENCES public.employees(employee_id) ON DELETE SET NULL,
  subject_name TEXT,
  category TEXT NOT NULL CHECK (category IN ('workplace','management','conduct','harassment','discrimination','safety','ethics','other')),
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 5 AND 160),
  description TEXT NOT NULL CHECK (char_length(description) BETWEEN 20 AND 10000),
  requested_outcome TEXT CHECK (requested_outcome IS NULL OR char_length(requested_outcome) <= 2000),
  priority TEXT NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted','under_review','escalated','resolved','closed')),
  hr_owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  escalated_to UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  escalated_to_name TEXT,
  escalated_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  resolution_summary TEXT CHECK (resolution_summary IS NULL OR char_length(resolution_summary) <= 4000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX complaints_reporter_idx ON public.complaints(reporter_id, created_at DESC);
CREATE INDEX complaints_hr_queue_idx ON public.complaints(status, priority, created_at DESC);

CREATE TABLE public.complaint_updates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_id UUID NOT NULL REFERENCES public.complaints(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  author_name TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'comment' CHECK (kind IN ('comment','status','escalation','resolution')),
  visibility TEXT NOT NULL DEFAULT 'reporter' CHECK (visibility IN ('reporter','internal')),
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX complaint_updates_case_idx ON public.complaint_updates(complaint_id, created_at);

CREATE OR REPLACE FUNCTION public.set_complaint_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER complaints_set_updated_at
BEFORE UPDATE ON public.complaints
FOR EACH ROW EXECUTE FUNCTION public.set_complaint_updated_at();

ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.complaint_updates ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.complaints, public.complaint_updates FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.complaints_case_number_seq FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON public.complaints TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.complaints_case_number_seq TO authenticated;
GRANT SELECT, INSERT ON public.complaint_updates TO authenticated;

CREATE POLICY complaints_read_authorized
ON public.complaints FOR SELECT
TO authenticated
USING (
  reporter_id = (SELECT auth.uid())
  OR EXISTS (
    SELECT 1 FROM public.profiles viewer
    WHERE viewer.id = (SELECT auth.uid()) AND viewer.role = 'admin'
  )
  OR (
    status = 'escalated'
    AND EXISTS (
      SELECT 1 FROM public.profiles viewer
      WHERE viewer.id = (SELECT auth.uid())
        AND viewer.role = 'executive'
        AND (escalated_to = viewer.id OR lower(coalesce(viewer.full_name, '')) LIKE '%faleh%')
    )
  )
);

CREATE POLICY complaints_reporter_insert
ON public.complaints FOR INSERT
TO authenticated
WITH CHECK (
  reporter_id = (SELECT auth.uid())
  AND reporter_role IN ('employee','manager')
  AND reporter_role = (SELECT role FROM public.profiles WHERE id = (SELECT auth.uid()))
  AND status = 'submitted'
  AND priority = 'normal'
  AND hr_owner_id IS NULL
  AND escalated_to IS NULL
  AND escalated_at IS NULL
  AND resolved_at IS NULL
  AND resolution_summary IS NULL
);

CREATE POLICY complaints_hr_update
ON public.complaints FOR UPDATE
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.profiles viewer WHERE viewer.id = (SELECT auth.uid()) AND viewer.role = 'admin')
)
WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles viewer WHERE viewer.id = (SELECT auth.uid()) AND viewer.role = 'admin')
);

CREATE POLICY complaint_updates_read_authorized
ON public.complaint_updates FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.complaints complaint
    JOIN public.profiles viewer ON viewer.id = (SELECT auth.uid())
    WHERE complaint.id = complaint_updates.complaint_id
      AND (
        viewer.role = 'admin'
        OR (complaint.reporter_id = viewer.id AND complaint_updates.visibility = 'reporter')
        OR (
          complaint.status = 'escalated'
          AND viewer.role = 'executive'
          AND (complaint.escalated_to = viewer.id OR lower(coalesce(viewer.full_name, '')) LIKE '%faleh%')
        )
      )
  )
);

CREATE POLICY complaint_updates_authorized_insert
ON public.complaint_updates FOR INSERT
TO authenticated
WITH CHECK (
  author_id = (SELECT auth.uid())
  AND EXISTS (
    SELECT 1
    FROM public.complaints complaint
    JOIN public.profiles author ON author.id = (SELECT auth.uid())
    WHERE complaint.id = complaint_updates.complaint_id
      AND (
        author.role = 'admin'
        OR (
          complaint.reporter_id = author.id
          AND complaint_updates.visibility = 'reporter'
          AND complaint_updates.kind = 'comment'
        )
        OR (
          complaint.status = 'escalated'
          AND author.role = 'executive'
          AND complaint_updates.visibility = 'internal'
          AND complaint_updates.kind = 'comment'
          AND (complaint.escalated_to = author.id OR lower(coalesce(author.full_name, '')) LIKE '%faleh%')
        )
      )
  )
);
